---
redirects:
  api: ./library/api/README.md
  api/overview: ./library/api/README.md
  api/project: ./library/api/README.md
  api/run: ./library/api/README.md
  artifacts/api: ./guides/artifacts/quickstart.md
  cli/overview: ./library/cli.md
  cli/restoring: ./library/cli.md
  docs/: ./README.md
  docs/getting-started: ./quickstart.md
  examples: ./library/example-projects/README.md
  frameworks/catalyst: ./integrations/catalyst.md
  frameworks/examples: ./examples.md
  frameworks/fastai: ./integrations/fastai/README.md
  frameworks/fastai-example: ./integrations/fastai.md
  frameworks/jax-example: ./library/example-projects/jax.md
  frameworks/keras: ./library/frameworks/keras.md
  frameworks/keras-example: ./library/example-projects/keras.md
  frameworks/numpy-example: ./library/example-projects/numpy.md
  frameworks/pytorch: ./library/frameworks/pytorch.md
  frameworks/pytorch-example: ./library/example-projects/pytorch.md
  frameworks/scikit: ./library/frameworks/scikit.md
  frameworks/scikit-example: ./library/example-projects/scikit.md
  frameworks/tensorflow: ./library/frameworks/tensorflow.md
  frameworks/tensorflow-example: ./library/example-projects/tensorflow.md
  frameworks/xgboost: ./library/frameworks/xgboost.md
  frameworks/xgboost-example: ./library/example-projects/xgboost.md
  getting-started: ./quickstart.md
  huggingface: ./integrations/huggingface.md
  java: ./ref/java/README.md
  java/wandbrun-builder: ./ref/java/wandbrun-builder.md
  java/wandbrun: ./ref/java/wandbrun.md
  library/advanced: ./guides/README.md
  library/advanced/grouping: ./library/grouping.md
  library/advanced/resuming: ./library/resuming.md
  library/advanced/security: ./library/security.md
  library/advanced/limits: ./library/limits.md
  library/api: ./ref/export-api/README.md
  library/api/examples: ./ref/export-api/examples.md
  library/reference: ./ref/README.md
  library/reference/wandb_api: ./ref/public-api/api.md
  library/reference/keras: ./ref/keras.md
  library/reference/data_types: ./ref/data-types/README.md
  library/reference/fastai: ./integrations/fastai/README.md
  library/sweeps: ./sweeps/overview.md
  library/sweeps/configuration: ./sweeps/configuration.md
  library/sweeps/advanced: ./sweeps/ray-tune.md
  library/sweeps/local-controller: ./sweeps/local-controller.md
  library/sweeps/python-api: ./sweeps/python-api.md
  library/example-projects: ./examples.md
  overview/company-faq: ./overview/company-faq.md
  overview/getting-help: ./overview/getting-help.md
  overview/overview: ./overview.md
  overview/technical-faq: ./overview/technical-faq.md
  sweeps/local: ./sweeps/local-controller.md
  sweeps/python: ./sweeps/python-api.md
  wandb/config: ./library/python/config.md
  wandb/init: ./library/python/init.md
  wandb/log: ./library/python/log.md
  wandb/restore: ./library/python/restore.md
  wandb/save: ./library/python/save.md
  library/integrations/pytorch: ./integrations/pytorch.md
  library/integrations/keras: ./integrations/keras.md
  library/integrations/tensorflow: ./integrations/tensorflow.md
  library/integrations/scikit: ./integrations/scikit.md
  library/integrations/fastai: ./integrations/fastai/README.md
  library/integrations/fastai/fastai: ./integrations/fastai/v1.md
  library/integrations/xgboost: ./integrations/xgboost.md
  library/integrations/lightgbm: ./integrations/lightgbm.md
  library/integrations/huggingface: ./integrations/huggingface.md
  library/integrations/tensorboard: ./integrations/tensorboard.md
  library/integrations/sagemaker: ./integrations/sagemaker.md
  library/integrations/lightning: ./integrations/lightning.md
  library/integrations/ignite: ./integrations/ignite.md
  library/integrations/kubeflow: ./integrations/kubeflow.md
  library/integrations/docker: ./integrations/docker.md
  library/integrations/jupyter: ./integrations/jupyter.md
  library/integrations/mlflow: ./integrations/mlflow.md
  library/integrations/databricks: ./integrations/databricks.md
  library/integrations/ray-tune: ./integrations/ray-tune.md
  library/integrations/catalyst: ./integrations/catalyst.md
  library/integrations/skorch: ./integrations/skorch.md
  library/integrations/simpletransformers: ./integrations/simpletransformers.md
  library/integrations/openai-gym: ./integrations/openai-gym.md
  library/integrations/numpy: ./integrations/numpy.md
  library/integrations/jax: ./integrations/jax.md
  ref/export-api: ./library/public-api-guide.md
  ref/export-api/api: ./ref/public-api/README.md
  ref/export-api/examples: ./library/public-api-guide.md
  alerts/slack: ./ref/app/features/alerts.md
  app/pages: ./ref/app/pages/README.md
  app/pages/project-page: ./ref/app/pages/project-page.md
  app/pages/workspaces: ./ref/app/pages/workspaces.md
  app/pages/run-page: ./ref/app/pages/run-page.md
  app/features: ./ref/app/features/README.md
  app/features/anon: ./ref/app/features/anon.md
  app/features/custom-charts: ./ref/app/features/custom-charts/README.md
  app/features/custom-charts/walkthrough: ./ref/app/features/custom-charts/walkthrough.md
  app/features/sidebar: ./ref/app/features/runs-table.md
  app/features/tags: ./ref/app/features/tags.md
  app/features/notes: ./ref/app/features/notes.md
  app/features/sweeps: ./ref/app/features/sweeps.md
  app/features/alerts: ./ref/app/features/alerts.md
  app/features/teams: ./ref/app/features/teams.md
  app/features/system-metrics: ./ref/app/features/system-metrics.md
  app/features/panels: ./ref/app/features/panels/README.md
  app/features/panels/code: ./ref/app/features/panels/code.md
  app/features/panels/parallel-coordinates: ./ref/app/features/panels/parallel-coordinates.md
  app/features/panels/compare-metrics: ./ref/app/features/panels/line-plot/README.md
  app/features/panels/compare-metrics/reference: ./ref/app/features/panels/line-plot/reference.md
  app/features/panels/compare-metrics/sampling-and-bucketing: ./ref/app/features/panels/line-plot/sampling.md
  app/features/panels/compare-metrics/smoothing: ./ref/app/features/panels/line-plot/smoothing.md
  app/features/panels/parameter-importance: ./ref/app/features/panels/parameter-importance.md
  app/features/panels/run-colors: ./ref/app/features/panels/run-colors.md
  app/features/panels/run-comparer: ./ref/app/features/panels/run-comparer.md
  app/features/panels/scatter-plot: ./ref/app/features/panels/scatter-plot.md
  
